In [1]:
import sqlite3
import pandas as pd
import numpy as np
import os
import sys
from datetime import timedelta, date, datetime

In [42]:
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

In [51]:
db = sqlite3.connect("../agg-data/unit-profile.db")

In [101]:
df = pd.DataFrame(columns=['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month'])
for unit_profile in [i for i in os.listdir() if i.startswith('Unit-Profile-')]:
    print(unit_profile)
    df_tmp = pd.read_excel(unit_profile)
    if unit_profile == 'Unit-Profile-Sept12.xls':
        df_tmp.rename(columns={'Download':'download', 'Upload':'upload', 'Technology':'technology', 'State':'state', 'Region':'region','UTC_OFFSET':'tz_offset','UTC_OFFSET_DST':'tz_offset_dst'}, inplace=True)
        df_tmp['year'] = '2012'
        df_tmp['month'] = '09'
        
    if unit_profile == 'Unit-Profile-Sept13.xlsx':
        df_tmp.rename(columns={'DOWN':'download', 'UP':'upload', 'TECHNOLOGY':'technology', 'STATE':'state', 'REGION':'region','timezone_offset':'tz_offset','timezone_offset_dst':'tz_offset_dst'}, inplace=True)
        df_tmp['year'] = '2013'
        df_tmp['month'] = '09'
        
    if unit_profile == 'Unit-Profile-Sept14.xls':
        df_tmp.rename(columns={'SK down':'download', 'SK UP':'upload', 'TECHNOLOGY':'technology', 'STATE':'state', 'REGION':'region','timezone_offset':'tz_offset','timezone_offset_dst':'tz_offset_dst'}, inplace=True)
        df_tmp['year'] = '2014'
        df_tmp['month'] = '09'
        
    if unit_profile == 'Unit-Profile-Apr12.xlsx':
        df_tmp.rename(columns={'UNIT_ID':'unit_id', 'ISP':'isp', 'DOWNLOAD_TIER':'download', 'UPLOAD_TIER':'upload', 'TECHNOLOGY':'technology', 'STATE':'state', 'REGION':'region','UTC_OFFSET':'tz_offset','UTC_OFFSET_DST':'tz_offset_dst'}, inplace=True)
        df_tmp['year'] = '2012'
        df_tmp['month'] = '04'
        
    if unit_profile == 'Unit-Profile-Sept15.xlsx':
        df_tmp.rename(columns={'Download':'download', 'Upload':'upload', 'TECHNOLOGY':'technology', 'STATE':'state', 'CENSUS':'region','timezone_offset':'tz_offset','timezone_offset_dst':'tz_offset_dst'}, inplace=True)
        df_tmp['year'] = '2015'
        df_tmp['month'] = '09'
        
    if unit_profile == 'Unit-Profile-Sept16.xlsx':
        df_tmp.rename(columns={'Download':'download', 'Upload':'upload', 'Technology':'technology', 'State':'state', 'Census':'region','timezone_offset':'tz_offset','timezone_offset_dst':'tz_offset_dst'}, inplace=True)
        df_tmp['year'] = '2016'
        df_tmp['month'] = '09'
        
    if unit_profile == 'Unit-Profile-Sept17.xlsx':
        df_tmp.rename(columns={'ISP':'isp', 'Download':'download', 'Upload':'upload', 'Technology':'technology', 'State':'state', 'Census':'region','timezone_offset':'tz_offset','timezone_offset_dst':'tz_offset_dst'}, inplace=True)
        df_tmp['year'] = '2017'
        df_tmp['month'] = '09'
        df_tmp['tz_offset'] = df_tmp['tz_offset'].str.replace(r' hr$', '')
        df_tmp['tz_offset_dst'] = df_tmp['tz_offset_dst'].str.replace(r' hr$', '')
        df_tmp['tz_offset'] = pd.to_numeric(df_tmp['tz_offset'])
        df_tmp['tz_offset_dst'] = pd.to_numeric(df_tmp['tz_offset_dst'])
    
    
    print(df_tmp.columns.tolist())
    print(df.columns.tolist())
    df_tmp['technology'] = df_tmp['technology'].str.upper()
    df_tmp['state'] = df_tmp['state'].str.upper()
    df_tmp['region'] = df_tmp['region'].str.upper()
    df_tmp = df_tmp[['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']]
    df = pd.concat([df, df_tmp], join='inner', axis=0, ignore_index=True)

Unit-Profile-Sept12.xls
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'Days', 'tz_offset', 'tz_offset_dst', 'year', 'month']
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']
Unit-Profile-Sept13.xlsx
['unit_id', 'isp', 'STATUS', 'download', 'upload', 'tz_offset', 'tz_offset_dst', 'state', 'region', 'technology', 'year', 'month']
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']
Unit-Profile-Sept14.xls
['unit_id', 'isp', 'technology', 'download', 'upload', 'tz_offset', 'tz_offset_dst', 'state', 'region', 'year', 'month']
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']
Unit-Profile-Apr12.xlsx
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'VALIDATED BY', 'DAYS', 'tz_offset', 'tz_offset_dst', 'year', 'month']
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']
Unit-Profile-Sept15.xlsx
['unit_id', 'isp', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'download', 'upload', 'year', 'month']
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']
Unit-Profile-Sept16.xlsx
['unit_id', 'isp', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'download', 'Download Lower Bound', 'Download Upper Bound', 'upload', 'year', 'month']
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']
Unit-Profile-Sept17.xlsx
['unit_id', 'isp', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'download', 'Download - Lower Bound', 'Download - Upper Bound', 'upload', 'WB Model', 'Whitebox can support download speed', 'Whitebox can support upload speed', 'year', 'month']
['unit_id', 'isp', 'download', 'upload', 'technology', 'state', 'region', 'tz_offset', 'tz_offset_dst', 'year', 'month']

In [99]:
df.tz_offset.value_counts()

-5         19675
-6         12533
-8          7198
-7          3320
-10          265
Unknown       35
-9             3
0              1
Name: tz_offset, dtype: int64

In [98]:
is_numeric_dtype(df.tz_offset)

False

In [102]:
df

,unit_id,isp,download,upload,technology,state,region,tz_offset,tz_offset_dst,year,month
0,6,Comcast,15,2,CABLE,UNKNOWN,UNKNOWN,-5,-4,2012,09
1,11,Verizon,35,35,FIBER,MA,NORTHEAST,-5,-4,2012,09
2,15,Verizon DSL,3,0.768,DSL,UNKNOWN,UNKNOWN,-5,-4,2012,09
3,358,Comcast,105,10,CABLE,VA,SOUTH,-5,-4,2012,09
4,360,Comcast,15,2,CABLE,VA,SOUTH,-5,-4,2012,09
5,361,Cablevision,30,5,CABLE,NY,NORTHEAST,-5,-4,2012,09
6,365,Cablevision,15,2,CABLE,NY,NORTHEAST,-5,-4,2012,09
7,368,AT&T,6,1,DSL,UNKNOWN,UNKNOWN,-6,-5,2012,09
8,372,Windstream,3,0.768,DSL,AR,SOUTH,-6,-5,2012,09
9,373,TimeWarner,10,1,CABLE,TX,SOUTH,-6,-5,2012,09
10,380,Charter,100,5,CABLE,MO,MIDWEST,-6,-5,2012,09
11,381,CenturyLink,1.5,0.512,DSL,MO,MIDWEST,-6,-5,2012,09
12,382,AT&T,0.768,0.128,DSL,SC,SOUTH,-5,-4,2012,09
13,384,Verizon DSL,3,0.768,DSL,MD,SOUTH,-5,-4,2012,09
14,386,Verizon,150,65,FIBER,MA,NORTHEAST,-5,-4,2012,09
15,389,TimeWarner,10,1,CABLE,WI,MIDWEST,-6,-5,2012,09
16,390,Verizon,15,5,FIBER,KY,SOUTH,-5,-4,2012,09
17,395,TimeWarner,50,5,CABLE,NY,NORTHEAST,-5,-4,2012,09
18,396,AT&T,12,1.5,DSL,CA,WEST,-8,-7,2012,09
19,397,Verizon,50,25,FIBER,NJ,NORTHEAST,-5,-4,2012,09
20,398,Comcast,15,2,CABLE,MI,MIDWEST,-5,-4,2012,09
21,405,AT&T,3,0.512,DSL,IL,MIDWEST,-6,-5,2012,09
22,408,Windstream,12,0.768,DSL,NC,SOUTH,-5,-4,2012,09
23,409,CenturyLink,1.5,0.256,DSL,MO,MIDWEST,-6,-5,2012,09
24,412,Verizon,15,5,FIBER,TX,SOUTH,-6,-5,2012,09
25,414,Comcast,25,4,CABLE,WA,WEST,-8,-7,2012,09
26,415,AT&T,6,0.512,DSL,GA,SOUTH,-5,-4,2012,09
27,416,Qwest,12,0.896,DSL,NM,WEST,-7,-6,2012,09
28,417,CenturyLink,3,0.64,DSL,FL,SOUTH,-5,-4,2012,09
29,418,AT&T,0.768,0.384,DSL,OK,SOUTH,-6,-5,2012,09
...,...,...,...,...,...,...,...,...,...,...,...
43000,27966,Windstream,3,0.384,DSL,NE,MIDWEST,-7,-6,2017,09
43001,999875,Windstream,3,0.384,DSL,TX,SOUTH,-6,-5,2017,09
43002,999903,Windstream,3,0.384,DSL,NC,SOUTH,-5,-4,2017,09
43003,1000089,Windstream,3,0.384,DSL,AR,SOUTH,-6,-5,2017,09
43004,999245,Windstream,3,0.384,DSL,KY,SOUTH,-5,-4,2017,09
43005,27147,Windstream,6,0.768,DSL,NM,WEST,-7,-6,2017,09
43006,999319,Windstream,3,0.384,DSL,IA,MIDWEST,-6,-5,2017,09
43007,942626,Windstream,6,0.768,DSL,OK,SOUTH,-6,-5,2017,09
43008,29723,Windstream,6,0.768,DSL,GA,SOUTH,-5,-4,2017,09
43009,939604,Windstream,6,0.768,DSL,GA,SOUTH,-5,-4,2017,09
43010,1000425,Windstream,6,0.512,DSL,OK,SOUTH,-6,-5,2017,09
43011,653484,Windstream,12,0.768,DSL,KY,SOUTH,-5,-4,2017,09
43012,797200,Windstream,12,1.5,DSL,TX,SOUTH,-6,-5,2017,09
43013,999329,Windstream,12,1.5,DSL,TX,SOUTH,-6,-5,2017,09
43014,997741,Windstream,12,1.5,DSL,IA,MIDWEST,-6,-5,2017,09
43015,999881,Windstream,12,0.768,DSL,PA,NORTHEAST,-5,-4,2017,09
43016,615302,Windstream,12,0.768,DSL,OK,SOUTH,-6,-5,2017,09
43017,619822,Windstream,12,0.768,DSL,MS,SOUTH,-6,-5,2017,09
43018,999661,Windstream,12,0.768,DSL,PA,NORTHEAST,-5,-4,2017,09
43019,999851,Windstream,12,1.5,DSL,TX,SOUTH,-6,-5,2017,09
43020,1010448,Windstream,12,0.768,DSL,GA,SOUTH,-5,-4,2017,09
43021,27915,Windstream,12,0.768,DSL,MN,MIDWEST,-6,-5,2017,09
43022,999889,Windstream,12,0.768,DSL,OK,SOUTH,-6,-5,2017,09
43023,615566,Windstream,12,0.768,DSL,OH,MIDWEST,-5,-4,2017,09
43024,797622,Windstream,12,0.768,DSL,NM,WEST,-7,-6,2017,09
43025,994689,Windstream,12,1.5,DSL,AR,SOUTH,-6,-5,2017,09
43026,216022,Windstream,12,0.768,DSL,IA,MIDWEST,-6,-5,2017,09
43027,215328,Windstream,12,0.768,DSL,PA,NORTHEAST,-5,-4,2017,09
43028,207618,Windstream,12,1.5,DSL,NC,SOUTH,-5,-4,2017,09
43029,29591,Windstream,16,1.5,DSL,OH,MIDWEST,-5,-4,2017,09

In [81]:
df.drop_duplicates(subset=['unit_id','isp','technology','state','region','year'], keep='last', inplace=True)

In [84]:
df[(df.year == '2012') & (df.unit_id == 26073)]

      unit_id   isp technology state region tz_offset tz_offset_dst  year
5220    26073   Cox      CABLE    CA   WEST        -8            -7  2012
25922   26073  AT&T        DSL    CA   WEST        -8            -7  2012

In [83]:
df[df.year == '2012'].unit_id.value_counts()

26073    2
773      2
9751     2
8100     2
10922    2
5355     2
27732    2
8804     2
12623    2
6759     2
8815     2
8117     2
12061    2
26722    2
12645    2
7410     2
26658    2
11936    2
30134    2
27240    2
7362     2
5455     2
731      2
29609    2
12184    2
5917     2
27672    2
27175    2
5505     2
8698     2
        ..
10959    1
27328    1
27329    1
10946    1
27331    1
27332    1
10949    1
10950    1
27336    1
27337    1
27338    1
10955    1
27340    1
27342    1
27344    1
27358    1
27345    1
27346    1
10963    1
27348    1
27349    1
27350    1
10967    1
27352    1
10969    1
27354    1
10971    1
27356    1
27357    1
27445    1
Name: unit_id, Length: 8416, dtype: int64

In [82]:
df[df.year == '2012'].unit_id.count() - df[df.year == '2012'].unit_id.nunique()

235

In [72]:
df[df.year == '2012'].unit_id.nunique()

8416

In [103]:
df.to_sql('unit-profile', db, if_exists='append', index=False)

In [18]:
df = pd.read_excel('Unit-Profile-Sept12.xls')

In [29]:
sept_unit_ids = set(df.unit_id.tolist())

In [25]:
sept_unit_ids[0] == 6

True

In [21]:
df_two = pd.read_excel('Unit-Profile-Apr12.xlsx')

In [28]:
apr_unit_ids = set(df_two.UNIT_ID.tolist())

In [30]:
sept_unit_ids < apr_unit_ids

False

In [31]:
sept_unit_ids > apr_unit_ids

False

In [32]:
len(sept_unit_ids & apr_unit_ids)

6635

In [33]:
len(sept_unit_ids)

7040

In [34]:
len(apr_unit_ids)

8011

In [44]:
df = pd.read_excel('Unit-Profile-Sept17.xlsx')

In [45]:
is_numeric_dtype(df.timezone_offset)

False

In [53]:
df = df[['unit_id','WB Model']]
df.rename(columns={'WB Model':'wb_model'}, inplace=True)

In [55]:
df.to_sql('whitebox_model', db, if_exists='append', index=False)